### ISSUE TITLE
[FEATURE] Nanotrasen and Minutemen comms channels

### ISSUE THREAD

**Issue by Apogee-dev** [shiptest-ss13/Shiptest#1249]
### Additional Info:

Requesting comms channels for Nanotrasen and Minutemen, and faction command headsets that include their respective keys to be given to officers on faction ships as a counterpart to the existing Solgov and Syndicate encryption keys. More faction parity, more options for events and ships.

**Comment by mel-byond** [comment]
I actually like this idea, shouldn't be too hard to implement.
Might do this as well as with my `adhoc_fallback` headsets idea I had in mind

**Comment by rye-rice** [comment]
I actually dont like the idea of global channels that can be used by anyone and communicate across z levels with not much effort. the reaosn why it works for centcom is because its only used for erts, and solgov was once only used by erts.

Though, faction specific wideband? That might be intresitng. Maybe a relay that must be put on a planet and actively powered for faction specific wideband to work?

**Comment by Ketrai** [comment]
Or specialized ships that provide their whole factions with comms. Honestly, there needs to be a bit more of a reason to play NT/minutemen right now anyways.

**Comment by Erikafox** [comment]
we did this
