### ISSUE TITLE
[BUG] Ruins have no atmosphere

### ISSUE THREAD

**Issue by Moltovz** [shiptest-ss13/Shiptest#1283]
## Testmerges:
#1141 
#1159 
#1173 
#1182 
#1067 
#1216 
#1170 
#1237 
#1128 
#1213 
#1206 
#132 
#1253 
## Reproduction:
go onto a planetary ruin, Im not sure exactly what ones are effected, but it is extremely common. 
![image](https://user-images.githubusercontent.com/61367602/176986111-529d963f-67ae-4d8f-a539-6bfeff67bc93.png)
![image](https://user-images.githubusercontent.com/61367602/176986117-eb27ed89-6d27-43f8-b973-99446e4ea450.png)
Unrelated, the Spider clan ruin on jungle planets has a space tile on the bottom right of it.

**Comment by Zevotech** [comment]
this is a known issue, it is caused by the way planets generate. Ruins generate before the planet fully loads, leading to them mostly spawning in space and having all internal atmos sucked out by the surrounding space tiles. When the planet finally generates around it, the ruin is already almost fully depressurized, leading to most mobs who were exposed to space dead on the floor. Ruins that are completely closed (with no external turfs included in the ruin) avoid this issue by simply generating as an already airtight environment. It is why the inside of ruins like the lifebringer ghostrole are still habitable while external turfs have no atmos.

**Comment by Zevotech** [comment]
oh and the spider clan ruins space tile was an unnoticed mistake on my part, pring a fix to that in like an hour anyways.
