### ISSUE TITLE
[BUG] nanoforged katana dash doesnt work after you do the do

### ISSUE THREAD

**Issue by triplezeta** [shiptest-ss13/Shiptest#32]
## Reproduction:

1. dash
2. the sheath gets locked
3. suffer.

**Comment by AsciiSquid** [comment]
Unable to recreate bug locally, sword does anime moves just fine.

If this is referring to the sheath locking if primed while in the belt slot, this is because you need to have the sheath in your active hand to dash. At best I can add a QoL feature to allow you to unprime the sheath while in the belt slot.
