### ISSUE TITLE
[BUG] Mining vendors give out stuff for free

### ISSUE THREAD

**Issue by TheNeoGamer42** [shiptest-ss13/Shiptest#368]
Issue reported from  Round ID: N/A

Reporting client version: 514.1557

Mining vendors give out shit for free. Specifically the newer ones ascii added.

![image](https://user-images.githubusercontent.com/58159167/138024420-92819dd1-8532-405d-9cbb-bc1cf4fc97b6.png)

This also results in advanced trollphysics where you buy the resupply vendor for this to get ALOT of free shit and a net gain of atleast a couple thousand credits.

**Comment by triplezeta** [comment]
sounds like the mining vendor selections should be rebalanced too.

**Comment by Sun-Soaked** [comment]
vendor selection balance is fine when it's functional- the issue is just freebies, and that specifically has to do with the fact that manually building mining vendors causes their cost to net to zero.
If I remember correctly from convos at the time, we actually removed them from most ships in the first place specifically because they were unlimited and that caused various troll physics exploits- so they should probably be safe to re-add now? 
Once this is fixed, at least.

**Comment by untrius** [comment]
This is actually all the vendors.  They have a check for if the vendor is on station that always returns false.  When the vendor isn't on station, everything is free.  The on station check touches a few different things, so it may not be the most simple fix in the world.
