### ISSUE TITLE
[FEATURE] Join Delay on Ship Spawn/Pre-emptive Memo/ShipName

### ISSUE THREAD

**Issue by ta3370** [shiptest-ss13/Shiptest#772]
## Name of feature: 
Ship Spawn Join Delay/Pre-naming/Memo-ing

### Related Pull Request on other codebase: 
N/A

### Additional Info:

It would be helpful to have some mechanic in place that made it more accessible to set Memo and Name, whether a 2 minute join delay after ship spawn, or the ability to pre-emptively set Memo and Name before it spawns. It's kind of disheartening when there's a mismatch between goals in the crew because literally over half a dozen people joined before you even got your face off the cryo floor to set the memo so they'd know what to expect of the ship and it's plans.

**Comment by Sinestia** [comment]
Why not simply have spawning disabled until enabled by the captain?

Maybe an initial state that still shows the ship in the spawn list, but with the name "Pending."

Of course, a popup or an inclusion into the ship purchasing menu would be ideal. Bit more work though since I believe you'd have to write a small tgui page to replace the input list for buying a ship to do this correctly.
